### ISSUE TITLE
Might make more sense to have the docs URL as the index.

### ISSUE THREAD

**Issue by lovelydinosaur** [marcgibbons/django-rest-framework-docs#1]
It's not immediately obvious that when you include it in the URL conf using...

```
url(r'^rest-api/', include('rest_framework_docs.urls')),
```

That the docs endpoint is actually...

```
rest-api/docs/
```

It might(?) be better to have the docs view at the index, so it's simply hosted at:

```
rest-api/
```

What do you think?

**Comment by marcgibbons** [comment]
Good call!

**Comment by marcgibbons** [comment]
Fixed
