### ISSUE TITLE
ImportError with django-rest-framework 2.3.2

### ISSUE THREAD

**Issue by jor123** [marcgibbons/django-rest-framework-docs#13]
In docs.py it tries to import a 'private' function `_camelcase_to_spaces` from django-rest-framework views.py

This was removed in https://github.com/tomchristie/django-rest-framework/commit/835d3f89d37b873b2ef96dc7d71922b035b07328#rest_framework/views.py

**Comment by marcgibbons** [comment]
Thanks for this note - haven't tried the latest version yet. Will look into it.

**Comment by marcgibbons** [comment]
This is now fixed in v0.1.5. Removed the dependency on DRF _camelcase_to_spaces
