### ISSUE TITLE
django-rest-framework-docs doesn't work with latest version of django-rest-framework

### ISSUE THREAD

**Issue by swistakm** [marcgibbons/django-rest-framework-docs#14]
Doesn't work with `2.3.4`. 

I've seen that @avinash240 already fixed it in [his fork](https://github.com/avinash240/django-rest-framework-docs). Maybe it's worth merging?

**Comment by avinash240** [comment]
There isn't much work to do to make this backwards compatible with older versions of django rest framework.  The only other issue I've found is there are a lot of calls in the original code of 'cls_instance.'  I'm not sure how that works, I couldn't get it to work myself and switch to using .cls.  This is my primary reason for not sending a pull request, if the author can clear that up I'll gladly send the pull request.

**Comment by marcgibbons** [comment]
Thanks for this - will look into it.

**Comment by marcgibbons** [comment]
Dear gents, I just pushed a new version using avinash240's fork. Added some conditions to check if the instances use 'cls' or 'cls_instance' as to work with both DRF <= v2.3. Let me know if it works out or if anything broke!

Many thanks,
Marc

**Comment by avinash240** [comment]
Any way I can get a contributor mention on this?

_Marlon_

**Comment by marcgibbons** [comment]
Totally!
Thanks for your help,
Marc
