### ISSUE TITLE
"Expected string or buffer" bug

### ISSUE THREAD

**Issue by alexf101** [marcgibbons/django-rest-framework-docs#15]
Immediately after following configuration instructions, I tried loading the main page, but encountered the following error screen.

rest_framework version: 2.3.4

TypeError at /
expected string or buffer
Request Method: GET
Request URL:    http://localhost:8000/
Django Version: 1.5.1
Exception Type: TypeError
Exception Value:  
expected string or buffer
Exception Location: /usr/lib/python2.7/re.py in sub, line 151
Python Executable:  /usr/bin/python
Python Version: 2.7.4
Python Path:  
['/home/alex/workspace/Masters/Fingerprints_django',
 '/home/alex/workspace/Masters/Fingerprints_django',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gst-0.10',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client',
 '/usr/lib/python2.7/dist-packages/ubuntuone-client',
 '/usr/lib/python2.7/dist-packages/ubuntuone-control-panel',
 '/usr/lib/python2.7/dist-packages/ubuntuone-couch',
 '/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol',
 '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode']
Server time:    Wed, 5 Jun 2013 18:00:15 +1000

**Comment by marcgibbons** [comment]
Interesting. Do your URL patterns have name attributes?

**Comment by marcgibbons** [comment]
Totally, that's it. I will push a fix! Thanks for reporting.

**Comment by marcgibbons** [comment]
In the meantime, give your URLs a name like this:
`url(r'countries/?$', api_views.CountryList.as_view(), name='list_of_countries'),`

**Comment by marcgibbons** [comment]
Fixed [https://github.com/marcgibbons/django-rest-framework-docs/commit/e0e4b8494c13c69b8e681b900e2250e5cf1937a7]

**Comment by alexf101** [comment]
Thanks!
