### ISSUE TITLE
Root URL showing trailing dollar sign.

### ISSUE THREAD

**Issue by lovelydinosaur** [marcgibbons/django-rest-framework-docs#3]
See the '/' endpoint in the included image.

![Screen Shot 2013-01-22 at 12 17 52](https://f.cloud.github.com/assets/647359/86179/cec7c8a2-648d-11e2-9179-5776187a5f54.png)

**Comment by marcgibbons** [comment]
Hmm... Can I see the url pattern ?

**Comment by lovelydinosaur** [comment]
You can replicate the issue by adding the docs to the finished rest framework tutorial: https://github.com/tomchristie/rest-framework-tutorial

URL patterns are listed here: https://github.com/tomchristie/rest-framework-tutorial/blob/master/tutorial/urls.py

**Comment by marcgibbons** [comment]
Fixed
