### ISSUE TITLE
'URLField' -> 'U R L Field'

### ISSUE THREAD

**Issue by lovelydinosaur** [marcgibbons/django-rest-framework-docs#5]
Noticed that for fieldnames like URLField, the splitting get applied incorrectly, leading to the field being listed as 'U R L Field'  (eg. as in the screenshot you've given)

There's a similar bit of code in REST framework do deal with translating view classes to names for the browseable API, which uses a regex which has marginally more correct behavior, which you might (or might not) want to reuse...

```
>>> import re
>>> field_name = 'URLField'
>>> CAMELCASE_BOUNDARY = '(((?<=[a-z])[A-Z])|([A-Z](?![A-Z]|$)))'
>>> print re.sub(CAMELCASE_BOUNDARY, ' \\1', field_name).strip()
URL Field
```

**Disclaimer**: Nope, I really don't remember exactly how that regex works. Black magic. :)

**Comment by marcgibbons** [comment]
Regex... so mysterious. Added the fix - thank you!
